handler.iden=BRB_IPS
crtPath=/home/payway/mobile/ipsCertificate.crt


casAuthUrl=https://172.16.201.31:8000/token
casRegisterUrl=https://172.16.201.31:8800/api/one-step/customers
casRemoveUrl=https://172.16.201.31:8800/api/customers/
casResolveUrl=https://172.16.201.31:8800/api/account

##casResolveUrl=https://117584f7-d6a6-4fba-8b4f-6de39810b73e.mock.pstmn.io/api/account?aliasType=MOBILE&aliasValue=%2B

pacs008DebetorUrl=https://172.16.201.31:8844/input/
checkOutpayment=https://172.16.201.31:8844/output/
rtp=https://172.16.201.31:8800/api/rtp-m/v1.0/RTPs/
qrrm.url=https://172.16.201.31:8800/api/qrr/v1.0/payee-qrc/
readQrcode=https://172.16.201.31:8800/api/qrr/v1.0/payee-qrc/

user=BKGFBIBIAXXX
password=123
senderBic=BKGFBIBI
receiver=BRBUBIBAXIPS
traceReference=xxx

walletcore.url=https://192.168.0.223:8463/amawalletmanagerws
walletcore.url.acceptType=application/json
walletcore.url.connectTimeout=10000
walletcore.url.mediaType=application/x-www-form-urlencoded
walletcore.url.readTimeout=10000
walletcore.url.gettoken=${walletcore.url}/oauth/token
walletcore.url.update=${walletcore.url}/v1/ama/trx/update
walletcore.url.updatepayment=${walletcore.url}/v1/payment/update

ips.qrcode.start.payment=https://172.16.201.31:8800/api/qrr/v1.0/extensions/
ips.limit.input.url=https://172.16.201.31:8844/input/
ips.limit.output.url=https://172.16.201.31:8844/output/
ips.qrcode.create=https://172.16.201.31:8800/api/qrr/v1.0/payee-qrc?isImageRequired=false

ips.incoming.input.url=https://172.16.201.31:8844/input/
walletcore.url.incoming.create=${walletcore.url}/v1/ama/payment/send
ips.incoming.output.url=https://172.16.201.31:8844/output/
ips.incoming.scheduler.enabled=false
walletcore.auth.username=ips
walletcore.auth.password=payway100
walletcore.auth.clientId=restapp
walletcore.auth.clientSecret=restapp

# IPS Signing
ips.signing.keystoreFile=/home/payway/mobile/BKGFBIBIAXXX_CMAIPSUser.pfx
ips.signing.keystorePass=FdMra#2026EAfs-
ips.signing.keyAlias=tq-cmaipsuser-871b3c9b-02ae-4a45-af7e-79525f9566d0
ips.signing.keyPass=FdMra#2026EAfs-